apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mf8vcns68-nodejs
  janus-idp.io/tekton: mf8vcns68-nodejs
  backstage.io/kubernetes-id: mf8vcns68-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mf8vcns68-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
